captcha_keypad.settings:
  type: mapping
  label: Settings
  mapping:
    captcha_keypad_code_size:
      type: integer
    captcha_keypad_shuffle_keypad:
      type: boolean
    captcha_keypad_forms:
      type: sequence
